#-------------------------------
# Site Settings
title: Chaos Inspired
logo: # You can add own logo. For example '/images/logo.png'.
author: Cat Lavigne
description: "todo: description here"


#-------------------------------
# Menu Settings
menu__settings:
  # menu__items:
  #   - title: 'About'
  #     url: '/about/'
  #   - title: 'Contact'
  #     url: '/contact/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Chaos Inspired
  hero__description:


#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: 
  portfolio__gallery:
    - image: /images/gallery-01.jpg
      images:
      - /images/gallery-01.jpg
      - /images/gallery-02.jpg
      - /images/gallery-03.jpg
      - /images/gallery-04.jpg
      - /images/gallery-05.jpg
      - /images/gallery-06.jpg
      title: Art title here
      slug: art-title-here
      description: Description of artwork here with <a href="https://unsplash.com/photos/8Od75hgzb9Y">link</a>

    - image: /images/gallery-02.jpg
      title: Paula Vermeulen
      description: Gray mountain covered by mountain <a href="https://unsplash.com/photos/_f2m3mEkaaU">Unsplash</a>

    - image: /images/gallery-03.jpg
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

    - image: /images/gallery-04.jpg
      title: Nord Wood
      description: White ceramic mug <a href="https://unsplash.com/photos/nDd3dIkkOLo">Unsplash</a>

    - image: /images/gallery-05.jpg
      title: Luca Bravo
      description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

    - image: /images/gallery-06.jpg
      title: Isaac Benhesed
      description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

    - image: /images/gallery-07.jpg
      title: Water Journal
      description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

    - image: /images/gallery-08.jpg
      title: Luca Bravo
      description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

    - image: /images/gallery-09.jpg
      title: Books and Laptop
      description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Join my mailing list for more chaos inspired art.<br />New art every week.
  mailchimp__identifier: gmail.us13.list-manage.com/subscribe/post?u=fc18de01bfe5bf3e88ed3a59c&amp;id=0b4094bc78&amp;f_id=0070a9e2f0 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
# social:
# - {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
# - {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
# - {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
# - {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
# - {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com"}
# - {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id